# Generated by Django 3.2.5 on 2022-05-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='relase_year',
            new_name='release_year',
        ),
    ]
